export const foodUnits: {id: number, unit: string} [] = [
    {id: 1, unit: "Gramm (g)"},
    {id: 2, unit: "Kilogramm (kg)"},
    {id: 3, unit: "Milligramm (mg)"},
    {id: 4, unit: "Mikrogramm (µg)"},
    {id: 5, unit: "Löffel"},
    {id: 6, unit: "Teelöffel (TL)"},
    {id: 7, unit: "Esslöffel (EL)"},
    {id: 8, unit: "Tasse"},
    {id: 9, unit: "Becher"},
    {id: 10, unit: "Glas"},
    {id: 11, unit: "Flasche"},
    {id: 12, unit: "Stück"},
    {id: 13, unit: "Portion"},
    {id: 14, unit: "Scheibe"},
    {id: 15, unit: "Schnitt"},
    {id: 16, unit: "Bund"},
    {id: 17, unit: "Prise"},
    {id: 18, unit: "Messerspitze"},
    {id: 19, unit: "Tropfen"},
    {id: 20, unit: "Handvoll"},
    {id: 21, unit: "Schuss"},
    {id: 22, unit: "Würfel"},
    {id: 23, unit: "Blatt"},
    {id: 24, unit: "Zehe"},
    {id: 25, unit: "Knolle"},
    {id: 26, unit: "Körner"},
    {id: 27, unit: "Tasse (gekocht)"},
    {id: 28, unit: "Tasse (roh)"},
    {id: 29, unit: "Schale"},
    {id: 30, unit: "Dose"},
    {id: 31, unit: "Packung"},
    {id: 32, unit: "Bündel"},
    {id: 33, unit: "Stange"},
    {id: 34, unit: "Rolle"},
    {id: 35, unit: "Tafel"},
    {id: 36, unit: "Fladen"},
    {id: 37, unit: "Streifen"},
    {id: 38, unit: "Ring"},
    {id: 39, unit: "Kugel"},
    {id: 40, unit: "Tröpfchen"},
    {id: 41, unit: "Spritze"}
]
