export interface Unit {
    id: number,
    unit: string,
}

export const foodUnits: { [id: number]: Unit } = {
    1: { id: 1, unit: "Gramm (g)" },
    2: { id: 2, unit: "Kilogramm (kg)" },
    3: { id: 3, unit: "Milligramm (mg)" },
    4: { id: 4, unit: "Mikrogramm (µg)" },
    5: { id: 5, unit: "Löffel" },
    6: { id: 6, unit: "Teelöffel (TL)" },
    7: { id: 7, unit: "Esslöffel (EL)" },
    8: { id: 8, unit: "Tasse" },
    9: { id: 9, unit: "Becher" },
    10: { id: 10, unit: "Glas" },
    11: { id: 11, unit: "Flasche" },
    12: { id: 12, unit: "Stück" },
    13: { id: 13, unit: "Portion" },
    14: { id: 14, unit: "Scheibe" },
    15: { id: 15, unit: "Schnitt" },
    16: { id: 16, unit: "Bund" },
    17: { id: 17, unit: "Prise" },
    18: { id: 18, unit: "Messerspitze" },
    19: { id: 19, unit: "Tropfen" },
    20: { id: 20, unit: "Handvoll" },
    21: { id: 21, unit: "Schuss" },
    22: { id: 22, unit: "Würfel" },
    23: { id: 23, unit: "Blatt" },
    24: { id: 24, unit: "Zehe" },
    25: { id: 25, unit: "Knolle" },
    26: { id: 26, unit: "Körner" },
    27: { id: 27, unit: "Tasse (gekocht)" },
    28: { id: 28, unit: "Tasse (roh)" },
    29: { id: 29, unit: "Schale" },
    30: { id: 30, unit: "Dose" },
    31: { id: 31, unit: "Packung" },
    32: { id: 32, unit: "Bündel" },
    33: { id: 33, unit: "Stange" },
    34: { id: 34, unit: "Rolle" },
    35: { id: 35, unit: "Tafel" },
    36: { id: 36, unit: "Fladen" },
    37: { id: 37, unit: "Streifen" },
    38: { id: 38, unit: "Ring" },
    39: { id: 39, unit: "Kugel" },
    40: { id: 40, unit: "Tröpfchen" },
    41: { id: 41, unit: "Spritze" }
};
